### 1. Import the NUMPY package under the name np.

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

<module 'numpy' from 'C:\\Users\\manue\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


### 2. Print the NUMPY version and the configuration.

In [6]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/manue/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/manue/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/manue/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/manue/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/manue/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/manue/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/manue/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/manue/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find? 

In [22]:
#Primera manera de conseguirlo, utilizando random.randint
#returns an array of random integers that are discrete uniform distribution of the specified dtype in the half-open interval [low, high).
a = np.random.randint(1,90,(2,4,5))
print(a)
a.shape

[[[81 89 46 46 73]
  [49 53 13 19 51]
  [16 69 11  5 66]
  [ 9 34 73 68 83]]

 [[61 46 36 34  8]
  [71 78 45 58 72]
  [ 8 49 75 27 68]
  [33 41  4 38 50]]]


(2, 4, 5)

In [14]:
#Segunda manera de conseguirlo, utilizando random
#generates random numbers from the standard uniform distribution
a = np.random.random((2,3,5))
print(a)
a.shape

[[[0.11216823 0.46081767 0.78501111 0.40558565 0.38237464]
  [0.1646271  0.20955995 0.24113629 0.31320288 0.68541401]
  [0.947796   0.53313931 0.46914345 0.92861038 0.27025716]]

 [[0.7939296  0.0014843  0.81093836 0.04683933 0.33689278]
  [0.09435884 0.83846545 0.81954421 0.88654675 0.28097478]
  [0.79073428 0.93005118 0.8660917  0.12554558 0.43353666]]]


(2, 3, 5)

In [109]:
#Tercera forma de conseguirlo, utilizando random.randn
#The values are always floating-point numbers based on the normal distribution having the mean equal to 0 and variation equal to 1.
a = np.random.randn(2,3,5)
print(a)
a.shape



[[[ 0.66257058  0.4946019   2.1097272   0.01016681  0.66119315]
  [ 1.18409744 -0.79161161 -0.38942521  2.81433625  0.88115269]
  [-0.54678915 -1.33254222  1.84392576  0.67006433 -0.44591254]]

 [[ 1.63855615  0.81954018  1.10389068 -0.07587799 -1.91980016]
  [ 2.17189986 -0.69400105 -0.60191439 -0.15562959  1.29803006]
  [ 1.18343062  0.80614288  0.22616513  0.75658704 -0.65558042]]]


(2, 3, 5)

# 4. Print a

In [110]:
print(a)

[[[ 0.66257058  0.4946019   2.1097272   0.01016681  0.66119315]
  [ 1.18409744 -0.79161161 -0.38942521  2.81433625  0.88115269]
  [-0.54678915 -1.33254222  1.84392576  0.67006433 -0.44591254]]

 [[ 1.63855615  0.81954018  1.10389068 -0.07587799 -1.91980016]
  [ 2.17189986 -0.69400105 -0.60191439 -0.15562959  1.29803006]
  [ 1.18343062  0.80614288  0.22616513  0.75658704 -0.65558042]]]


# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
# Assign the array to variable "b"

In [111]:
b = np.ones((5,2,3))
b.shape
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 6. Print b

In [112]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 7. Do a and b have the same size? How do you prove that in Python code?

In [113]:
print(a.shape)
print(b.shape)
#a == b usando este comparador devolvería un array del mismo tamaño que a y b formado por booleanos indicando si el elemento correspondiente coincide en ambos arrays
#hago uso de la funcion np.all para comparar
if np.all(a.shape == b.shape):
    print('a y b tienen el mismo tamaño')
else:
    print('No lo tienen')
    

(2, 3, 5)
(5, 2, 3)
No lo tienen


# 8. Are you able to add a and b? Why or why not?

In [114]:
c = np.add(a,b)
#Tienen diferentes shapes (2,3,5) (5,2,3

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [115]:
b.shape

(5, 2, 3)

In [116]:
c = b.reshape(2, 3, 5)


In [117]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [118]:
d = np.add(a,c)
print(d)

[[[ 1.66257058  1.4946019   3.1097272   1.01016681  1.66119315]
  [ 2.18409744  0.20838839  0.61057479  3.81433625  1.88115269]
  [ 0.45321085 -0.33254222  2.84392576  1.67006433  0.55408746]]

 [[ 2.63855615  1.81954018  2.10389068  0.92412201 -0.91980016]
  [ 3.17189986  0.30599895  0.39808561  0.84437041  2.29803006]
  [ 2.18343062  1.80614288  1.22616513  1.75658704  0.34441958]]]


In [119]:
9e-01


0.9

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [120]:
print(a)
print(d)
#Unos estan representados en notacion cientifica que es en la forma en la que trabaja Numpy

[[[ 0.66257058  0.4946019   2.1097272   0.01016681  0.66119315]
  [ 1.18409744 -0.79161161 -0.38942521  2.81433625  0.88115269]
  [-0.54678915 -1.33254222  1.84392576  0.67006433 -0.44591254]]

 [[ 1.63855615  0.81954018  1.10389068 -0.07587799 -1.91980016]
  [ 2.17189986 -0.69400105 -0.60191439 -0.15562959  1.29803006]
  [ 1.18343062  0.80614288  0.22616513  0.75658704 -0.65558042]]]
[[[ 1.66257058  1.4946019   3.1097272   1.01016681  1.66119315]
  [ 2.18409744  0.20838839  0.61057479  3.81433625  1.88115269]
  [ 0.45321085 -0.33254222  2.84392576  1.67006433  0.55408746]]

 [[ 2.63855615  1.81954018  2.10389068  0.92412201 -0.91980016]
  [ 3.17189986  0.30599895  0.39808561  0.84437041  2.29803006]
  [ 2.18343062  1.80614288  1.22616513  1.75658704  0.34441958]]]


# 12. Multiply a and c. Assign the result to e

In [121]:
print(a.shape)
print(c.shape)


(2, 3, 5)
(2, 3, 5)


In [142]:
c = c.reshape(2,3,5)
a = a.reshape(2,5,3)
print(c.shape)
print(a.shape)

(2, 3, 5)
(2, 5, 3)


In [140]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [143]:
e = np.dot(a,c)
print(e)

[[[[ 3.26689967  3.26689967  3.26689967  3.26689967  3.26689967]
   [ 3.26689967  3.26689967  3.26689967  3.26689967  3.26689967]]

  [[ 1.8554574   1.8554574   1.8554574   1.8554574   1.8554574 ]
   [ 1.8554574   1.8554574   1.8554574   1.8554574   1.8554574 ]]

  [[ 1.63329943  1.63329943  1.63329943  1.63329943  1.63329943]
   [ 1.63329943  1.63329943  1.63329943  1.63329943  1.63329943]]

  [[-0.99817869 -0.99817869 -0.99817869 -0.99817869 -0.99817869]
   [-0.99817869 -0.99817869 -0.99817869 -0.99817869 -0.99817869]]

  [[ 2.06807756  2.06807756  2.06807756  2.06807756  2.06807756]
   [ 2.06807756  2.06807756  2.06807756  2.06807756  2.06807756]]]


 [[[ 3.56198702  3.56198702  3.56198702  3.56198702  3.56198702]
   [ 3.56198702  3.56198702  3.56198702  3.56198702  3.56198702]]

  [[ 0.17622171  0.17622171  0.17622171  0.17622171  0.17622171]
   [ 0.17622171  0.17622171  0.17622171  0.17622171  0.17622171]]

  [[-1.45154503 -1.45154503 -1.45154503 -1.45154503 -1.45154503]
   [-1.45

# 13. Does e equal to a? Why or why not?

In [144]:
print(a)
print(e)
#las dimensiones de e son 2 matrices con 5 filas y 3 columnas
#las dimensiones de a son 10 matrices, con 2 filas y 5 columnas
if np.all(e.shape == a.shape):
    print('a y b tienen el mismo tamaño')
else:
    print('No lo tienen')

[[[ 0.66257058  0.4946019   2.1097272 ]
  [ 0.01016681  0.66119315  1.18409744]
  [-0.79161161 -0.38942521  2.81433625]
  [ 0.88115269 -0.54678915 -1.33254222]
  [ 1.84392576  0.67006433 -0.44591254]]

 [[ 1.63855615  0.81954018  1.10389068]
  [-0.07587799 -1.91980016  2.17189986]
  [-0.69400105 -0.60191439 -0.15562959]
  [ 1.29803006  1.18343062  0.80614288]
  [ 0.22616513  0.75658704 -0.65558042]]]
[[[[ 3.26689967  3.26689967  3.26689967  3.26689967  3.26689967]
   [ 3.26689967  3.26689967  3.26689967  3.26689967  3.26689967]]

  [[ 1.8554574   1.8554574   1.8554574   1.8554574   1.8554574 ]
   [ 1.8554574   1.8554574   1.8554574   1.8554574   1.8554574 ]]

  [[ 1.63329943  1.63329943  1.63329943  1.63329943  1.63329943]
   [ 1.63329943  1.63329943  1.63329943  1.63329943  1.63329943]]

  [[-0.99817869 -0.99817869 -0.99817869 -0.99817869 -0.99817869]
   [-0.99817869 -0.99817869 -0.99817869 -0.99817869 -0.99817869]]

  [[ 2.06807756  2.06807756  2.06807756  2.06807756  2.06807756]
   

# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [145]:
print(d)

[[[ 1.66257058  1.4946019   3.1097272   1.01016681  1.66119315]
  [ 2.18409744  0.20838839  0.61057479  3.81433625  1.88115269]
  [ 0.45321085 -0.33254222  2.84392576  1.67006433  0.55408746]]

 [[ 2.63855615  1.81954018  2.10389068  0.92412201 -0.91980016]
  [ 3.17189986  0.30599895  0.39808561  0.84437041  2.29803006]
  [ 2.18343062  1.80614288  1.22616513  1.75658704  0.34441958]]]


In [147]:
d_max = d.max()
print(d_max)

3.8143362523469775


In [148]:
d_min = d.min()
print(d_min)

-0.9198001640434883


In [149]:
d_mean = d.mean()
print(d_mean)

1.457566479338291


# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`

In [152]:
f = np.empty((2,3,5))
print(f.shape)

(2, 3, 5)


In [154]:
print(d_max)
print(d_min)
print(d_mean)

3.8143362523469775
-0.9198001640434883
1.457566479338291


# 16 . Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [160]:
f = 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 0 * (d == d_min) + 100 * (d == d_max) + 50 * (d == d_mean)

In [161]:
print(f)

[[[ 75  75  75  25  75]
  [ 75  25  25 100  75]
  [ 25  25  75  75  25]]

 [[ 75  75  75  25   0]
  [ 75  25  25  25  75]
  [ 75  75  25  75  25]]]


# 17. Print d and f. Do you have your expected f?

For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [162]:
print(d)
print(f)

[[[ 1.66257058  1.4946019   3.1097272   1.01016681  1.66119315]
  [ 2.18409744  0.20838839  0.61057479  3.81433625  1.88115269]
  [ 0.45321085 -0.33254222  2.84392576  1.67006433  0.55408746]]

 [[ 2.63855615  1.81954018  2.10389068  0.92412201 -0.91980016]
  [ 3.17189986  0.30599895  0.39808561  0.84437041  2.29803006]
  [ 2.18343062  1.80614288  1.22616513  1.75658704  0.34441958]]]
[[[ 75  75  75  25  75]
  [ 75  25  25 100  75]
  [ 25  25  75  75  25]]

 [[ 75  75  75  25   0]
  [ 75  25  25  25  75]
  [ 75  75  25  75  25]]]


# 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be: