In [292]:
#1. Import the NUMPY package under the name np.
%pip install numpy
import numpy as np



Note: you may need to restart the kernel to use updated packages.


In [301]:

#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())



1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/axell/anaconda3/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/axell/anaconda3/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/axell/anaconda3/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/axell/anaconda3/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/axell/anaconda3/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/axell/anaconda3/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/axell/anaconda3/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/axell/anaco

In [302]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

import random

a = np.random.random((2, 3, 5))

#4. Print a.
print(a)
a.shape

[[[0.16700061 0.49768465 0.23904729 0.76987872 0.25325187]
  [0.37650636 0.62227297 0.26197326 0.57409859 0.81944921]
  [0.00604313 0.44337642 0.9894077  0.4400566  0.08012912]]

 [[0.18409311 0.76297379 0.32346022 0.66679981 0.82704517]
  [0.53603306 0.00677796 0.75970062 0.44644792 0.40089921]
  [0.0458874  0.55329605 0.01801528 0.43293765 0.34412357]]]


(2, 3, 5)

In [303]:
np.empty([2, 3, 5])

array([[[0.16700061, 0.49768465, 0.23904729, 0.76987872, 0.25325187],
        [0.37650636, 0.62227297, 0.26197326, 0.57409859, 0.81944921],
        [0.00604313, 0.44337642, 0.9894077 , 0.4400566 , 0.08012912]],

       [[0.18409311, 0.76297379, 0.32346022, 0.66679981, 0.82704517],
        [0.53603306, 0.00677796, 0.75970062, 0.44644792, 0.40089921],
        [0.0458874 , 0.55329605, 0.01801528, 0.43293765, 0.34412357]]])

In [304]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))

#6. Print b.

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [305]:
#7. Do a and b have the same size? How do you prove that in Python code?

a.size == b.size

True

In [306]:
#8. Are you able to add a and b? Why or why not?

c = a + b

#Because there matrices don't match collumns + lines (a has 3 columns when b has 2 lines. b has 5 columns when a has 3 lines )

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [307]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
b = np.ones((5, 2, 3))
c = np.transpose(b, (1,2,0))
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [308]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c
# works because same shape
print(d)

[[[1.16700061 1.49768465 1.23904729 1.76987872 1.25325187]
  [1.37650636 1.62227297 1.26197326 1.57409859 1.81944921]
  [1.00604313 1.44337642 1.9894077  1.4400566  1.08012912]]

 [[1.18409311 1.76297379 1.32346022 1.66679981 1.82704517]
  [1.53603306 1.00677796 1.75970062 1.44644792 1.40089921]
  [1.0458874  1.55329605 1.01801528 1.43293765 1.34412357]]]


In [309]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print("a", a)
print("d",d)
# difference is of +1. Because b = a + a matriz of ones.

a [[[0.16700061 0.49768465 0.23904729 0.76987872 0.25325187]
  [0.37650636 0.62227297 0.26197326 0.57409859 0.81944921]
  [0.00604313 0.44337642 0.9894077  0.4400566  0.08012912]]

 [[0.18409311 0.76297379 0.32346022 0.66679981 0.82704517]
  [0.53603306 0.00677796 0.75970062 0.44644792 0.40089921]
  [0.0458874  0.55329605 0.01801528 0.43293765 0.34412357]]]
d [[[1.16700061 1.49768465 1.23904729 1.76987872 1.25325187]
  [1.37650636 1.62227297 1.26197326 1.57409859 1.81944921]
  [1.00604313 1.44337642 1.9894077  1.4400566  1.08012912]]

 [[1.18409311 1.76297379 1.32346022 1.66679981 1.82704517]
  [1.53603306 1.00677796 1.75970062 1.44644792 1.40089921]
  [1.0458874  1.55329605 1.01801528 1.43293765 1.34412357]]]


In [310]:
#12. Multiply a and c. Assign the result to e.
e = a * c

In [311]:
#13. Does e equal to a? Why or why not?
a == e

# It is equal because c is just the transpose of b in the shape of a. And b was ones. So a * c was the multiplication of a by a matriz of ones of the same shape. 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [334]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

meann = d.mean()
maxx = d.max()
minn = d.min()


In [335]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty_like(d)
print(f)

[[[0.16700061 0.49768465 0.23904729 0.76987872 0.25325187]
  [0.37650636 0.62227297 0.26197326 0.57409859 0.81944921]
  [0.00604313 0.44337642 0.9894077  0.4400566  0.08012912]]

 [[0.18409311 0.76297379 0.32346022 0.66679981 0.82704517]
  [0.53603306 0.00677796 0.75970062 0.44644792 0.40089921]
  [0.0458874  0.55329605 0.01801528 0.43293765 0.34412357]]]


In [336]:
"""
#16. Populate the values in f. 
For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

"\n#16. Populate the values in f. \nFor each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n"

In [360]:
# if >min and <mean : = 25 
# if >mean and < max :  = 75
# if =mean : = 50
# if min : = 0
# if max: =100

f = np.where(d == minn , 0, np.where(d < meann, 25, np.where(d == meann, 50, np.where(d < maxx, 75, np.where(d == maxx,100,0)))))


In [361]:

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(d)
print(f)

[[[1.16700061 1.49768465 1.23904729 1.76987872 1.25325187]
  [1.37650636 1.62227297 1.26197326 1.57409859 1.81944921]
  [1.00604313 1.44337642 1.9894077  1.4400566  1.08012912]]

 [[1.18409311 1.76297379 1.32346022 1.66679981 1.82704517]
  [1.53603306 1.00677796 1.75970062 1.44644792 1.40089921]
  [1.0458874  1.55329605 1.01801528 1.43293765 1.34412357]]]
[[[ 25  75  25  75  25]
  [ 25  75  25  75  75]
  [  0  75 100  75  25]]

 [[ 25  75  25  75  75]
  [ 75  25  75  75  25]
  [ 25  75  25  75  25]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""