#1. Import the NUMPY package under the name np.

In [13]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [2]:
print(np.version.version)

1.21.5


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))

#4. Print a.

In [4]:
print(a)

[[[0.88313732 0.41737686 0.83967383 0.93387497 0.59165726]
  [0.1440056  0.68590106 0.05326875 0.87657581 0.88110279]
  [0.56081423 0.15051172 0.25970786 0.0347735  0.66864602]]

 [[0.07955621 0.53060336 0.44044386 0.21162784 0.7715549 ]
  [0.24827807 0.28476482 0.2511393  0.92421003 0.47695457]
  [0.31678464 0.27584596 0.71984924 0.80792544 0.87791197]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [5]:
b = np.ones((5,2,3))


#6. Print b.

In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [29]:
a == b

/var/folders/qc/t82_vk1d72zgwrn06427c8bc0000gn/T/ipykernel_4187/160026346.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a == b


False

#8. Are you able to add a and b? Why or why not?

In [28]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [24]:
c = b.transpose(1,2,0)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [27]:
d = sum(a + c)

print(d)

[[2.96269353 2.94798022 3.28011769 3.14550281 3.36321216]
 [2.39228366 2.97066588 2.30440806 3.80078584 3.35805736]
 [2.87759887 2.42635768 2.9795571  2.84269893 3.54655799]]


#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
print(a)


print('---------')


print(d)

[[[0.88313732 0.41737686 0.83967383 0.93387497 0.59165726]
  [0.1440056  0.68590106 0.05326875 0.87657581 0.88110279]
  [0.56081423 0.15051172 0.25970786 0.0347735  0.66864602]]

 [[0.07955621 0.53060336 0.44044386 0.21162784 0.7715549 ]
  [0.24827807 0.28476482 0.2511393  0.92421003 0.47695457]
  [0.31678464 0.27584596 0.71984924 0.80792544 0.87791197]]]
---------
[[2.96269353 2.94798022 3.28011769 3.14550281 3.36321216]
 [2.39228366 2.97066588 2.30440806 3.80078584 3.35805736]
 [2.87759887 2.42635768 2.9795571  2.84269893 3.54655799]]


#12. Multiply a and c. Assign the result to e.

In [39]:
e = (a * c)

print(e)

[[[0.88313732 0.41737686 0.83967383 0.93387497 0.59165726]
  [0.1440056  0.68590106 0.05326875 0.87657581 0.88110279]
  [0.56081423 0.15051172 0.25970786 0.0347735  0.66864602]]

 [[0.07955621 0.53060336 0.44044386 0.21162784 0.7715549 ]
  [0.24827807 0.28476482 0.2511393  0.92421003 0.47695457]
  [0.31678464 0.27584596 0.71984924 0.80792544 0.87791197]]]


#13. Does e equal to a? Why or why not?

In [40]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [47]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print('max is', d_max)
print('---')
print('min is', d_min)
print('---')
print('mean is', d_mean)

max is 3.8007858378217474
---
min is 2.3044080553238597
---
mean is 3.0132318516172365


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [66]:
f = np.empty_like(d)
print(f)

[[2.96269353 2.94798022 3.28011769 3.14550281 3.36321216]
 [2.39228366 2.97066588 2.30440806 3.80078584 3.35805736]
 [2.87759887 2.42635768 2.9795571  2.84269893 3.54655799]]


#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [81]:
d_min, d_max, d_mean = d.min(), d.max(), d.mean()
f[(d > d_min)|(d < d_mean)] = 25
f[(d > d_mean)|(d < d_max)] = 75
f[(d == d_mean)] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(f)

[[ 75.  75.  75.  75.  75.]
 [ 75.  75.   0. 100.  75.]
 [ 75.  75.  75.  75.  75.]]
