In [2]:
#1. Import the NUMPY package under the name np.

In [3]:
%pip install numpy
import numpy as np

You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [4]:
#2. Print the NUMPY version and the configuration.
%pip show numpy



Name: numpy
Version: 1.24.1
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Requires: 
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [5]:
#3. Generate a 2x3x5 3-dimensional array with random values. 
# Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate 
# random arrays. How many ways can you find?

'''veo que hay diferentes extensiones de random.
lalalala pero que la más apropiada para esto creo que es esta, 
las demás no termino de entenderlas, sobre todo .seed
'''

a =np.random.random((2, 3, 5))


In [6]:
#4. Print a.
a

array([[[0.23918042, 0.47814937, 0.44452317, 0.32875893, 0.77297573],
        [0.09831625, 0.64700782, 0.10210378, 0.47684854, 0.36266692],
        [0.90949248, 0.5683263 , 0.23716186, 0.267879  , 0.16592215]],

       [[0.53772738, 0.21132519, 0.65143491, 0.63480319, 0.05259498],
        [0.23374224, 0.65425563, 0.48292672, 0.54782242, 0.85891024],
        [0.55420794, 0.86944255, 0.45908278, 0.41173044, 0.9672434 ]]])

In [7]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b =np.ones((5, 2, 3))

In [8]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
#7. Do a and b have the same size? How do you prove that in Python code?

if np.array_equal(a.shape, b.shape):
    print("Both arrays have the same shape: ", a.shape)
else:
    print("Both arrays have different shape: ", a.shape, "and", b.shape)

Both arrays have different shape:  (2, 3, 5) and (5, 2, 3)


In [10]:
#8. Are you able to add a and b? Why or why not?
'''
No puedo porque el primer indice no es el mismo, el primer numero que entiendo 
que es el numero de filas es diferente y creo que es por eso que no deja

'''


'\nNo puedo porque el primer indice no es el mismo, el primer numero que entiendo \nque es el numero de filas es diferente y creo que es por eso que no deja\n\n'

In [11]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.reshape(b,(2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [12]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = np.concatenate((c, a), axis=0)
d

# Ahora funciona porque tienen la misma size


array([[[1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ]],

       [[1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ]],

       [[0.23918042, 0.47814937, 0.44452317, 0.32875893, 0.77297573],
        [0.09831625, 0.64700782, 0.10210378, 0.47684854, 0.36266692],
        [0.90949248, 0.5683263 , 0.23716186, 0.267879  , 0.16592215]],

       [[0.53772738, 0.21132519, 0.65143491, 0.63480319, 0.05259498],
        [0.23374224, 0.65425563, 0.48292672, 0.54782242, 0.85891024],
        [0.55420794, 0.86944255, 0.45908278, 0.41173044, 0.9672434 ]]])

In [13]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print (a)
print (d)
'''
uno es a y el otro la suma de a y c . el a sigue teniendo una size de 2,3,5 
mientras que d tiene una size de 4,3,5

'''

[[[0.23918042 0.47814937 0.44452317 0.32875893 0.77297573]
  [0.09831625 0.64700782 0.10210378 0.47684854 0.36266692]
  [0.90949248 0.5683263  0.23716186 0.267879   0.16592215]]

 [[0.53772738 0.21132519 0.65143491 0.63480319 0.05259498]
  [0.23374224 0.65425563 0.48292672 0.54782242 0.85891024]
  [0.55420794 0.86944255 0.45908278 0.41173044 0.9672434 ]]]
[[[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[0.23918042 0.47814937 0.44452317 0.32875893 0.77297573]
  [0.09831625 0.64700782 0.10210378 0.47684854 0.36266692]
  [0.90949248 0.5683263  0.23716186 0.267879   0.16592215]]

 [[0.53772738 0.21132519 0.65143491 0.63480319 0.05259498]
  [0.23374224 0.65425563 0.48292672 0.54782242

'\nuno es a y el otro la suma de a y c . el a sigue teniendo una size de 2,3,5 \nmientras que d tiene una size de 4,3,5\n\n'

In [14]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a, c)
e



array([[[0.23918042, 0.47814937, 0.44452317, 0.32875893, 0.77297573],
        [0.09831625, 0.64700782, 0.10210378, 0.47684854, 0.36266692],
        [0.90949248, 0.5683263 , 0.23716186, 0.267879  , 0.16592215]],

       [[0.53772738, 0.21132519, 0.65143491, 0.63480319, 0.05259498],
        [0.23374224, 0.65425563, 0.48292672, 0.54782242, 0.85891024],
        [0.55420794, 0.86944255, 0.45908278, 0.41173044, 0.9672434 ]]])

In [15]:
#13. Does e equal to a? Why or why not?
'''
Si, porque c seguía siendo todo numeros 1
 
'''



'\nSi, porque c seguía siendo todo numeros 1\n \n'

In [16]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

max = np.amax(d)
max

1.0

In [17]:
min = np.amin (d)
min

0.05259498351204528

In [18]:
mean = np.mean (d)
mean

0.7371093788255859

In [19]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))
f

array([[[0.23918042, 0.47814937, 0.44452317, 0.32875893, 0.77297573],
        [0.09831625, 0.64700782, 0.10210378, 0.47684854, 0.36266692],
        [0.90949248, 0.5683263 , 0.23716186, 0.267879  , 0.16592215]],

       [[0.53772738, 0.21132519, 0.65143491, 0.63480319, 0.05259498],
        [0.23374224, 0.65425563, 0.48292672, 0.54782242, 0.85891024],
        [0.55420794, 0.86944255, 0.45908278, 0.41173044, 0.9672434 ]]])

In [20]:
"""
#16. Populate the values in f. For each value in d, 
# if it's larger than d_min but smaller than d_mean, assign 25 to 
# the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 
to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

en la matriz f tiene que quedar 
 
25  if d_min < e < d_mean
75  if d_mean < e < d_max
50  if e = d_mean
0   if e = d_min
100 if e = d_max

"""

"\n#16. Populate the values in f. For each value in d, \n# if it's larger than d_min but smaller than d_mean, assign 25 to \n# the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 \nto the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n\nen la matriz f tiene que quedar \n \n25  if d_min < e < d_mean\n75  if d_mean < e < d_max\n50  if e = d_mean\n0   if e = d_min\n100 if e = d_max\n\n"

In [21]:
'''
#16. Populate the values in f. For each value in d, 

25  if d_min < e < d_mean
75  if d_mean < e < d_max
50  if e = d_mean
0   if e = d_min
100 if e = d_max
'''



'\n#16. Populate the values in f. For each value in d, \n\n25  if d_min < e < d_mean\n75  if d_mean < e < d_max\n50  if e = d_mean\n0   if e = d_min\n100 if e = d_max\n'

In [22]:
print(d)

[[[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[0.23918042 0.47814937 0.44452317 0.32875893 0.77297573]
  [0.09831625 0.64700782 0.10210378 0.47684854 0.36266692]
  [0.90949248 0.5683263  0.23716186 0.267879   0.16592215]]

 [[0.53772738 0.21132519 0.65143491 0.63480319 0.05259498]
  [0.23374224 0.65425563 0.48292672 0.54782242 0.85891024]
  [0.55420794 0.86944255 0.45908278 0.41173044 0.9672434 ]]]


In [ ]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            e = d[i][j][k]
            if d_min < e < d_mean:
                f[i][j][k] = 25
            elif d_mean < e < d_max:
                f[i][j][k] = 75
            elif e == d_mean:
                f[i][j][k] = 50
            elif e == d_min:
                f[i][j][k] = 0
            elif e == d_max:
                f[i][j][k] = 100
print(d)
print(f)






# he entendido que es esto porque me lo ha explicado Carlos, espero recordarlo mañana.

In [23]:

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'