#1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [2]:
print(np.version.version)

1.21.5


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
#Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2, 3, 5))

#4. Print a.

In [4]:
print(a)

[[[0.97406117 0.79985052 0.19127278 0.14968415 0.48996757]
  [0.24453817 0.21364328 0.19700443 0.95558636 0.78461205]
  [0.64025474 0.25310534 0.483676   0.10802373 0.40653242]]

 [[0.22541307 0.83245978 0.62813706 0.79620211 0.46332068]
  [0.55826464 0.07283076 0.52204589 0.57846786 0.29153616]
  [0.55337331 0.41475841 0.48480169 0.22443061 0.37287129]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"


In [5]:
b = np.ones((5, 2, 3))

#6. Print b.

In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [7]:
print(a.size)
print(b.size)

30
30


#8. Are you able to add a and b? Why or why not?

In [8]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [9]:
c = b.transpose(1, 2, 0)
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [10]:
d = a + c
print(d)

# It works because the structure of both arrays is the same. 

[[[1.97406117 1.79985052 1.19127278 1.14968415 1.48996757]
  [1.24453817 1.21364328 1.19700443 1.95558636 1.78461205]
  [1.64025474 1.25310534 1.483676   1.10802373 1.40653242]]

 [[1.22541307 1.83245978 1.62813706 1.79620211 1.46332068]
  [1.55826464 1.07283076 1.52204589 1.57846786 1.29153616]
  [1.55337331 1.41475841 1.48480169 1.22443061 1.37287129]]]



#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [11]:
print(d)

[[[1.97406117 1.79985052 1.19127278 1.14968415 1.48996757]
  [1.24453817 1.21364328 1.19700443 1.95558636 1.78461205]
  [1.64025474 1.25310534 1.483676   1.10802373 1.40653242]]

 [[1.22541307 1.83245978 1.62813706 1.79620211 1.46332068]
  [1.55826464 1.07283076 1.52204589 1.57846786 1.29153616]
  [1.55337331 1.41475841 1.48480169 1.22443061 1.37287129]]]


In [12]:
print(a)

# The array d is a+1, as we add a np.ones array with same size to a.

[[[0.97406117 0.79985052 0.19127278 0.14968415 0.48996757]
  [0.24453817 0.21364328 0.19700443 0.95558636 0.78461205]
  [0.64025474 0.25310534 0.483676   0.10802373 0.40653242]]

 [[0.22541307 0.83245978 0.62813706 0.79620211 0.46332068]
  [0.55826464 0.07283076 0.52204589 0.57846786 0.29153616]
  [0.55337331 0.41475841 0.48480169 0.22443061 0.37287129]]]


#12. Multiply a and c. Assign the result to e.

In [27]:
e = a * c

print(e)


[[[0.97406117 0.79985052 0.19127278 0.14968415 0.48996757]
  [0.24453817 0.21364328 0.19700443 0.95558636 0.78461205]
  [0.64025474 0.25310534 0.483676   0.10802373 0.40653242]]

 [[0.22541307 0.83245978 0.62813706 0.79620211 0.46332068]
  [0.55826464 0.07283076 0.52204589 0.57846786 0.29153616]
  [0.55337331 0.41475841 0.48480169 0.22443061 0.37287129]]]


#13. Does e equal to a? Why or why not?

In [14]:
# Yes, because you are multiplying by an array full of 1s, and both arrays have the same structure,
# so the can be multiplyied element by element. 

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [15]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [20]:
f = np.empty((2, 3, 5))

#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.

Note: you don't have to use Numpy in this question.




In [25]:
print(d)

print(len(d))

f.shape

[[[1.97406117 1.79985052 1.19127278 1.14968415 1.48996757]
  [1.24453817 1.21364328 1.19700443 1.95558636 1.78461205]
  [1.64025474 1.25310534 1.483676   1.10802373 1.40653242]]

 [[1.22541307 1.83245978 1.62813706 1.79620211 1.46332068]
  [1.55826464 1.07283076 1.52204589 1.57846786 1.29153616]
  [1.55337331 1.41475841 1.48480169 1.22443061 1.37287129]]]
2


(2, 3, 5)

In [28]:
for i in range(len(d)):
    
    for j in range(len(d[i])):
        
        for k in range(len(d[i][j])):
            
            e = d[i][j][k]

            if d_min < e < d_mean:

                f[i][j][k] = 25

            elif d_mean < e < d_max:

                f[i][j][k] = 75

            elif e == d_mean:

                f[i][j][k] = 50

            elif e == d_min:

                f[i][j][k] = 0

            elif e == d_max:

                f[i][j][k] = 100
        
print(d)
print(f)

[[[1.97406117 1.79985052 1.19127278 1.14968415 1.48996757]
  [1.24453817 1.21364328 1.19700443 1.95558636 1.78461205]
  [1.64025474 1.25310534 1.483676   1.10802373 1.40653242]]

 [[1.22541307 1.83245978 1.62813706 1.79620211 1.46332068]
  [1.55826464 1.07283076 1.52204589 1.57846786 1.29153616]
  [1.55337331 1.41475841 1.48480169 1.22443061 1.37287129]]]
[[[100.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  25.  75.  25.  25.]]

 [[ 25.  75.  75.  75.  25.]
  [ 75.   0.  75.  75.  25.]
  [ 75.  25.  75.  25.  25.]]]


#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question