# 1. Import the NUMPY package under the name np.

In [63]:
import numpy as np


# 2. Print the NUMPY version and the configuration.

In [64]:
np.__version__

'1.21.5'

In [65]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/ronaldhernandez/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/ronaldhernandez/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/ronaldhernandez/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/ronaldhernandez/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/ronaldhernandez/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/ronaldhernandez/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/ronaldhernandez/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/ronaldhernandez/opt/anaconda3/in

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

In [66]:
a = np.random.random((2, 3, 5))

# 4. Print a.

In [67]:
print(a)

[[[0.87393032 0.98410269 0.27493604 0.81068025 0.24683397]
  [0.07326881 0.2370159  0.30679171 0.51751539 0.18956735]
  [0.47853877 0.47442594 0.46997717 0.39844971 0.46658051]]

 [[0.12769204 0.30712572 0.56625696 0.59867254 0.07004132]
  [0.92042292 0.73752577 0.01971155 0.55997105 0.39680436]
  [0.12456192 0.07473361 0.42529185 0.5270777  0.04778918]]]


# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [68]:
b = np.ones((5, 2, 3))

#6. Print b.

In [69]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 7. Do a and b have the same size? How do you prove that in Python code?

In [70]:
a.size

30

In [71]:
b.size

30

# 8. Are you able to add a and b? Why or why not?

In [72]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [73]:
c = b.transpose(1, 2, 0)

print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [74]:
d = np.add(a, c)

print(d)

[[[1.87393032 1.98410269 1.27493604 1.81068025 1.24683397]
  [1.07326881 1.2370159  1.30679171 1.51751539 1.18956735]
  [1.47853877 1.47442594 1.46997717 1.39844971 1.46658051]]

 [[1.12769204 1.30712572 1.56625696 1.59867254 1.07004132]
  [1.92042292 1.73752577 1.01971155 1.55997105 1.39680436]
  [1.12456192 1.07473361 1.42529185 1.5270777  1.04778918]]]


# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [75]:
print(a, d) # se le ha sumado a todos los valores, el valor de 1, que correspondia al al arrai b en un principio

[[[0.87393032 0.98410269 0.27493604 0.81068025 0.24683397]
  [0.07326881 0.2370159  0.30679171 0.51751539 0.18956735]
  [0.47853877 0.47442594 0.46997717 0.39844971 0.46658051]]

 [[0.12769204 0.30712572 0.56625696 0.59867254 0.07004132]
  [0.92042292 0.73752577 0.01971155 0.55997105 0.39680436]
  [0.12456192 0.07473361 0.42529185 0.5270777  0.04778918]]] [[[1.87393032 1.98410269 1.27493604 1.81068025 1.24683397]
  [1.07326881 1.2370159  1.30679171 1.51751539 1.18956735]
  [1.47853877 1.47442594 1.46997717 1.39844971 1.46658051]]

 [[1.12769204 1.30712572 1.56625696 1.59867254 1.07004132]
  [1.92042292 1.73752577 1.01971155 1.55997105 1.39680436]
  [1.12456192 1.07473361 1.42529185 1.5270777  1.04778918]]]


# 12. Multiply a and c. Assign the result to e.

In [76]:
e = np.multiply(a, c)

print(e)

[[[0.87393032 0.98410269 0.27493604 0.81068025 0.24683397]
  [0.07326881 0.2370159  0.30679171 0.51751539 0.18956735]
  [0.47853877 0.47442594 0.46997717 0.39844971 0.46658051]]

 [[0.12769204 0.30712572 0.56625696 0.59867254 0.07004132]
  [0.92042292 0.73752577 0.01971155 0.55997105 0.39680436]
  [0.12456192 0.07473361 0.42529185 0.5270777  0.04778918]]]


# 13. Does e equal to a? Why or why not?

si, es exactamente la misma!


# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [ ]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max, d_min, d_mean)

1.9696321103521537 1.0208804620236025 1.5260261326126476


# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [ ]:
f = np.empty((2, 3, 5))

print(f)

[[[0.19668262 0.58885485 0.96963211 0.15109353 0.70482493]
  [0.48021272 0.57613102 0.72102571 0.68367504 0.12013812]
  [0.12589627 0.89710934 0.44600305 0.69481065 0.15054269]]

 [[0.412625   0.1046005  0.36798211 0.82070574 0.84196559]
  [0.83688805 0.86817916 0.30147533 0.85412591 0.73668437]
  [0.02088046 0.44886794 0.82663721 0.47803081 0.35450315]]]


# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [ ]:

f = np.where(d == d_max, 100, np.where(d > d_mean, 75, np.where(d == d_mean, 50, np.where(d > d_min, 25, 0))))


# 17. Print d and f. Do you have your expected f?
For instance, if your d is:

In [ ]:
print(d)

print(f)

[[[1.19668262 1.58885485 1.96963211 1.15109353 1.70482493]
  [1.48021272 1.57613102 1.72102571 1.68367504 1.12013812]
  [1.12589627 1.89710934 1.44600305 1.69481065 1.15054269]]

 [[1.412625   1.1046005  1.36798211 1.82070574 1.84196559]
  [1.83688805 1.86817916 1.30147533 1.85412591 1.73668437]
  [1.02088046 1.44886794 1.82663721 1.47803081 1.35450315]]]
[[[ 25  75 100  25  75]
  [ 25  75  75  75  25]
  [ 25  75  25  75  25]]

 [[ 25  25  25  75  75]
  [ 75  75  25  75  75]
  [  0  25  75  25  25]]]
